# encoding: utf-8

Section.delete_all
Section.create!(name: "Campus Services")
Section.create!(name: "College Committees")
Section.create!(name: "Community Affairs")
Section.create!(name: "Diversity")
Section.create!(name: "Graduate Committees")
Section.create!(name: "Health")
Section.create!(name: "Safety & Security")
Section.create!(name: "Student Activities")
Section.create!(name: "Student Activities Funding Bodies")
Section.create!(name: "Student Affairs")
Section.create!(name: "Student Government")
Section.create!(name: "Student Government Committees")
Section.create!(name: "Student Government Assembly Committees")
sections = Section.all
section = sections[0]

Committee.delete_all

Committee.create!(section: section, name: "Campus Services: Banking", info: "The Campus Services Committee of Student Government meets with representatives from Citibank and the University Bursar as needed to discuss issues of banking services for students and to provide feedback about the current level of service and the present and future needs of the student community.", contact: "Student Government, sg-contact@uchicago.edu")
Committee.create!(section: section, name: "Campus Services: Bookstore", info: "The Campus Services Committee of Student Government meets with representatives from Citibank and the University Bursar as needed to discuss issues of banking services for students and to provide feedback about the current level of service and the present and future needs of the student community.", contact: "Student Government, sg-contact@uchicago.edu")
Committee.create!(section: section, name: "Campus Dining Advisory Board", info: "
The Campus Dining Advisory Board provides oversight and student response for the quality and structure of the Campus Dining Services administered by Housing and Dining Services. Student surveys and focus groups have helped steer the administration in choosing the dining plan, menu, and layout. Students on the Dining Advisory Board meet monthly with administrators and discuss \"big-picture issues.\" They provide feedback to the management of the dining venues, consider proposals for changes in services, assist in planning for future changes (brands, prices, selections), and offer feedback about policies and procedures that affect the cost and structure of the meal plans. Three administrators plus six students comprise the committee. Students are appointed by the Inter-House Council and Student Government. They meet 2-3 times per quarter.", contact_info: "Richard Mason, Director of Operations and Communications, Campus Dining Services", website: "http://housing.uchicago.edu/")

Committee.create!(section: section, name: "Housing Activities Resource Council (HARC)", info: "HARC was created by the Office of Undergraduate Student Housing to subsidize events involving two or more Houses from different residence halls. Their purpose is to distribute funds from Housing to promote inter-House interaction and programming. HARC board representatives are elected from each residence hall, for a total membership of 10 undergraduate students. The board reviews applications for funding and allocates a quarterly budget for approved inter-House activities. The number of members is 10. They meet weekly, except for Finals Week of each quarter.", contact_info: "Joe Edwards, Assistant Director of the University House System, jredward@uchicago.edu", website: "http://harc.uchicago.edu")

Committee.create!(section: section, name: "Inter-House Council (IHC)", info: "The IHC is a body that represents the undergraduate population living in the housing system (about 60% of the College) on issues such as dining, housing, and transportation. There are a number of committees that deal directly with those three issues in cooperation with the housing staff and the relevant companies with which the University contracts. Other committees that have existed include the printing committee, reviewing the upcoming switch to pay printing at USITE, and one dealing with the further integration of Court Theater into the University community. The IHC also holds events, such as the annual Tug-O-War and the always hilarious roommate game. These events build interhouse unity, interhouse rivalries, and serve as an important conduit of free food to the undergraduate population. Later in the year, IHC will also sponsors an annual blood drive. One student representative is elected to IHC by each House, for a total membership of 38 students. They meet weekly, except for Finals Week of each quarter. An executive committee of 5 officers is elected by the general body.", contact_info: "Katie Callow-Wright, Director of Undergraduate Student Housing, ccallow@uchicago.edu

Charles Stephen Thompson, President, cst85@uchicago.edu", website: "http://housing.uchicago.edu/college_houses/student_leadership.shtml")

Committee.create!(section: section, name: "Library Student Resource Group (LSRG)", info: "The purpose of the Library Student Resource Group is to open a formal channel of communication between students and the Library Administration. The LSRG discusses matters related to all the University libraries—Crerar, D’Angelo Law, Eckhart, Harper, Regenstein, SSAd, and Yerkes—including feedback about collections, access, services, and present and future needs of the student community. The LSRG also assists in making specific recommendations to improve the Library and considers proposals for future changes in services. Finally, members of the LSRG discuss how the Library can most effectively communicate its resources, services and plans with students, and conversely, how students can most effectively communicate their wishes, needs and concerns to the Library.

The student representation in the LSRG consists of: 4 students from the College, 4 graduate students (one from each of the Divisions—Biological Sciences, Physical Sciences, Social Sciences, and Humanities), and up to 6 students from the Professional Schools (Divinity, GSB, Harris, Law, Pritzker, SSA). The Council also includes several Library administration staff: Jim Vaughan, Assistant Director for Access & Facilities, Sem Sutter, Assistant Director for Humanities & Social Sciences, John Kimbrough, Assistant to the Director of the University Library, and Judith Nadler, the Director of the University Library, who chairs the group.The Council meets approximately 2 times per quarter. Students are appointed to the Council by Deans of Students, working with the Office of the Vice President and Dean of Students, and serve a 2-year term.", contact_info: "Jim Vaughan, Assistant Director for Access and Facilities Services, Regenstein Library, j-vaughan@uchicago.edu", website: "http://www.lib.uchicago.edu/e/about/studadv/index.html")

Committee.create!(section: section, name: "Transportation Student Advisory Board", info: "The Transportation Student Advisory Board, chaired by representatives from Student Government (SG) and Inter House Council (IHC), provides a channel for students to continually evaluate campus transportation systems. Three students are appointed by SG and three students are appointed by IHC. Students will work with Brian Shaw, Director of Campus Transportation and Parking Services. The group meets 2 times per quarter.", contact_info: "Deb Garfi, Associate Director of Transportation and Parking, dgarfi@uchicago.edu")

Committee.create!(section: section, name: "Campus Services Committee", info: "The Committee on Campus Services addresses concerns pertaining to transportation, security, dining, on campus banking, and academics at the University. Members interested in transportation will work with Chicago Transit Authority (CTA) and the Administrative Transportation committees including the Late Night Transportation Committee and Transportation Advisory Work Group in order to improve the transit routes to, from and around campus as well as parking lot space. From the A-F route, the 171/2/3 and the Late Night Van Service, members of this committee will ensure the campus transportation system is working effectively at all times and for all students. Other members will work sit on and work closely with UofC Committee on Safety and Security, Independent Review Committee for the UCPD, and the All University Disciplinary committee with the aim of creating a safe environment for all members of the University. In the area of dining, members will serve on the university Campus Dining Advisory Board which will focus on oversight and student response on the quality and structure on the Campus Dining Services. Members interested in banking will have an opportunity to work with the university bursar and the manager of Citibank with the purpose of advising the administration on issues of banking services provided to students.Members will also deal with academic services on campus including Cmore, course evaluations and class times and availability. Past contributions from the Committee on Campus Services include the development of a new events website that is expected to launch in 2006, leading a project to install a camera on the side of Eckhart and an LCD screen in the Reynolds Club to display information and allow people to watch for the buses while waiting inside during the winter, Created http://factoids.uchicago.edu to disseminate useful facts for students, Categorized and prioritized student complaints to NSIT about cMail, and audited the Regenstein library facilities problems (broken thermostats, etc.) and reported them to Facilities Services, along with various other facilities problems around campus.", contact_info: "Chris Williams, Campus Services Chair, chriswilliams@uchicago.edu", website: "http://sg.uchicago.edu/")



section = sections[1]

Committee.create!(section: section, name: "College Council of Student Government (SG)", info: "The College Council is the undergraduate representative body of Student Government. The purpose of the College Council is to advocate for the betterment of the undergraduate student body of the University of Chicago and bring the concerns of individual constituencies to the attention of the Administration. The council meets at 6 pm every Wednesday in Stuart Hall and together with the Graduate Council, as the full Student Government Assembly, on the first Wednesday of each month in GSB Classroom 004. The Council is composed of 15 positions: four first-year class officers, four second-year class officers, three third-year class officers, three fourth-year class officers, and one \"nth\"-year class officer.", contact_info: "Jay Kim, Chair, jaykim@uchicago.edu", website: "http://sg.uchicago.edu")

Committee.create!(section: section, name: "College Dean of Students Advisory Council", info: "The Dean's Advisory Council is a group of students that meet with the Dean of Students in the College, Susan Art, and various College advisors to discuss a wide variety of issues that influence student life. The council's main focus is improving academic and campus life for students at the University. We encourage critical dialogue but do not expect to make the council a forum for complaints or unilateral changes. We discuss issues ranging from life in housing, how students select courses, or how the University reacts to student deaths. In particular, this group focuses on issues that are not addressed by Student Government, Inter House Council, or other bodies of student representatives. There are ten students and six advisers. The council meets three times per quarter, and the students meet another three times on their own. Students are nominated by advisors, Resident Heads, and RSOs, and final selection is made by the current Council Chair and Secretary.", contact_info: "Bonnie Kanter, Adviser in the College, bonniek@uchicago.edu", website: "http://sg.uchicago.edu/assembly/")

Committee.create!(section: section, name: "Maroon Key Society", info: "The College's honorary society. Members serve as advisers to the Dean of the College, the Dean of Students in the College, and the Associate Dean of the College for Student Life. The Society advises the College on a range of issues including curricular and co-curricular life. Nominees must be second or third year students in the College who have been especially active in co-curricular activities, who have good communication skills, and whose academic performance has been strong with a minimum overall grade point average of 3.0. Inductees receive a commemorative pin and are honored at the College Honors Awards Assembly. Selection is made by the College Student Leader Awards Committee. The membership is comprised of about 40-50 third- and fourth-years. They meet two times per quarter.", contact_info: "Lori Hurvitz, Director of the College Programming Office,l-hurvitz@uchicago.edu")
Committee.create!(section: section, name: "Senior Class Gift Committee", info: " The Senior Class Gift (SCG) Committee is the organizing force behind the success of the Senior Class Gift Campaign. The committee works directly with the Office of Development and Alumni Relations in helping lead the class to participate in giving back to the College. The Senior Class Gift benefits the College Fund which supports important programs and priorities of the College including financial aid, study abroad programs, internships and faculty support. Fourth Years are nominated to serve on the committee by various College administrators, but all seniors are encouraged to volunteer if interested. Approximately 15-25 students serve on the committee. Meetings are bi-monthly in the beginning of the academic year and more frequent during the Spring quarter.", contact_info: "Josh Levine, Assistant Director of Student and Young Alumni Giving,jlevine@development.uchicago.edu")
Committee.create!(section: section, name: "Committee on Academic Affairs of Student Government (SG)", info: "The Student Government Academics Committee meets twice a month and works for all students, College and graduate, to improve the academic life here at the University of Chicago . In the past, we have helped bring Microsoft Word to the library computers, expand All-Night Study Space into Finals Week, and get a one-time transcript fee. For the future, the committee continues to work to unify the online academic resources on campus. This includes modifying course evaluations, bringing course syllabi online and creating a course search engine to better serve the University community. The committee's largest and most challenging endeavor is the Online Syllabi Project, an initiative to move all course syllabi/documents online. By joining the committee, you'll have the chance to work closely with university administrators and professors to further develop this online system that will enable students to not only \"virtually\" shop for courses, but also to know at a glance the course requirements, syllabi, and course schedule.", contact_info: "Toussaint Losier, SG VP for Administration, tlosier@uchicago.edu", website: "http://sg.uchicago.edu/committees/")
Committee.create!(section: section, name: "Humanities Collegiate Division Student Advisory Committee", info: "The goal of the Humanities Collegiate Division Student Advisory Committee is to provide feedback to the HCD administration about various initiatives and academic life within the Humanities Collegiate Division. The number of members is 8-10 and the Committee meets as needed. Department chairs nominate students and the HCD Master appoints the interested students.", contact: "Thomas Christensen, Master of the Humanities Collegiate Division, tchriste@uchicago.edu")
Committee.create!(section: section, name: "Undergraduate Order of the \"C\"", info: "All undergraduate men lettering in a varsity sport are members. The purpose of the Order of the \"C\" is to support Varsity athletics and its student-athletes through program development and promotion of the University's athletics program. The membership is also involved in fundraising and community service in the Hyde Park and greater Chicagoland areas. The organization is represented by a board made up of seven elected executive members (President, VP, Treasurer, Secretary, Special Events Chair, two Concessions Coordinators) as well as two representatives from each of the 11 varsity sports. The board meets bi-weekly and also attends annual meetings with its alumni counterpart, the Graduate Order of the \"C\".", contact_info: "Scott Wiercinski, Advisor, swiercinski@uchicago.edu", website: "http://orderofc.uchicago.edu")
Committee.create!(section: section, name: "Women's Athletic Association (WAA)", info: "All women participating in a varsity sport are members. The purpose of the WAA is to support varsity athletics and to promote and develop the University's athletics program. The organization is composed of a student elected executive board and two team representatives from each varsity sport. This organization serves as the campus Student Athlete Advisory Committee (SAAC) and the President (or designee) represents the University of Chicago on the University Athletic Association conference SAAC. The group meets bi-weekly as an Executive Board, and monthly with team representatives.", contact_info: "Rosalie R. Resch, Advisor,rresch@uchicago.edu", website: "http://athletics.uchicago.edu/waa/waa.htm")
Committee.create!(section: section, name: "Committee on College Discipline", info: "The Committee on College Discipline is appointed by Susan Art, the Dean of Students in the College, in accordance with legislation passed by the College Council in 1970. It consists of seven faculty members, two undergraduate student members, and the Dean of Students in the College (or his or her appointed representative), who participates in the meetings of the Committee but has no vote. A quorum consists of three faculty members. The committee convenes as necessary.", contact_info: "Susan Art, Dean of Students in the College, art3@uchicago.edu")
Committee.create!(section: section, name: "Housing Activities Resource Council (HARC)", info: "HARC was created by the Office of Undergraduate Student Housing to subsidize events involving two or more Houses from different residence halls. Their purpose is to distribute funds from Housing to promote inter-House interaction and programming. HARC board representatives are elected from each residence hall, for a total membership of 10 undergraduate students. The board reviews applications for funding and allocates a quarterly budget for approved inter-House activities. The number of members is 10. They meet weekly, except for Finals Week of each quarter.", contact_info: "Joe Edwards, Assistant Director of the University House System, jredward@uchicago.edu", website: "http://harc.uchicago.edu")

Committee.create!(section: section, name: "Inter-House Council (IHC)", info: "The IHC is a body that represents the undergraduate population living in the housing system (about 60% of the College) on issues such as dining, housing, and transportation. There are a number of committees that deal directly with those three issues in cooperation with the housing staff and the relevant companies with which the University contracts. Other committees that have existed include the printing committee that reviewed the switch to pay printing at USITE and a committee to deal with the further integration of Court Theater into the University community. The IHC also holds events, such as the annual Tug-O-War and the always hilarious roommate game. These events build interhouse unity, interhouse rivalries, and serve as an important conduit of free food to the undergraduate population. Later in the year, IHC will also sponsors an annual blood drive. One student representative is elected to IHC by each House, for a total membership of 38 students. They meet weekly, except for finals week of each quarter. An executive committee of five officers is elected by the general body.", contact_info: "Katie Callow-Wright, Director of Undergraduate Student Housing, ccallow@uchicago.edu 
Charles Stephen Thompson, President, cst85@uchicago.edu", website: "http://housing.uchicago.edu/college_houses/student_leadership.shtml")



section = sections[2]



Committee.create!(section: section, name: "Community Service Fund (CSF)", info: "CSF provides grants to University Community Service Recognized Student Organizations (CSRSOs) and to community service projects by Recognized Student Organizations (RSOs). There are 55 CSRSOs eligible to apply for funds for community service initiatives. The CSF selection committee consisting of Student Government, CSRSO and University Community Service Center (UCSC) representatives who meet quarterly to review funding for that specific quarter and once annually to review year-long CSRSO funding proposals. CSF Annual Allocations are limited to CSRSOs.", contact_info: "Wallace E. Goode, Jr., Director, UCSC, wgoode@uchiago.edu", website: "http://communityservice.uchicago.edu/")



section = sections[3]
Committee.create!(section: section, name: "Office of Multicultural Student Affairs Advisory Board", info: " The purpose of the Office of Multicultural Student Affairs (OMSA) Advisory Board is to advise the director of OMSA and the administration on the needs of students of color, the problems/issues currently facing students of color and to advise OMSA on areas of programming currently being done. The Advisory Board will consist of 15-20 students that are selected from applications submitted to the Director of OMSA. Both undergraduate and graduate students interested in issues around diversity are welcome to apply. The Advisory Board will meet twice a month during the academic year.", contact_info: "Ana Vázquez, Deputy Dean of Students in the University, Director of the Office of Multicultural Student Affairs,avazquez@uchicago.edu")
Committee.create!(section: section, name: "Office of Multicultural Student Affairs Allocations Board", info: " The purpose of the Office of Multicultural Student Affairs (OMSA) Allocations Board is to provide support to programming efforts by the University's cultural recognized student organizations (RSOs) that are consistent with and enhance the mission of OMSA. The Board will consist of 10-15 students actively involved in cultural RSOs.", contact_info: "Rosa Ortiz, Assistant Director, Office of Multicultural Student Affairs, ryo@uchicago.edu")


section = sections[4]

Committee.create!(section: section, name: "Graduate Council (GC) of Student Government (SG) ", info: "The Graduate Council is the graduate student half of the Assembly of the Student Government of the University of Chicago. It is made up of 17 representatives chosen by the various professional schools and graduate divisions. The number of seats on the council depends on the enrollment in the division, though every division is guaranteed one seat. Among its many purposes is the planning and funding of events that involve students from across the divisions and schools to encourage inter-divisional interaction. In past years, in addition to large on-campus events such as the annual spring barbecue, GC-sponsored events have included bowling nights, First Fridays at the MCA, a discussion panel series, ice skating on the midway, and other events paid for or subsidized by the Graduate Council with its share of the student activities fee. The GC also helps other campus organizations publicize their events to graduate students throughout the University. 

In addition to this programming aspect, the Graduate Council serves as an intermediary between graduate students and the administration. As a representative body, it creates a space in which students from the several professional schools and divisions can identify areas of mutual concern and discuss possible solutions. Because of its position within Student Government, it is able to maintain a high level of dialogue with administrators. One of the important responsibilities of Council members is to assist in the appointing of graduate student members to standing committees that cover a variety of issues affecting all students. Many of these are Student Government committees, such as the Student Government Finance Committee, which oversees funding allocations to RSOs throughout the year, while others function outside SG and throughout the University.
                  
GC represents half of the larger Student Government Assembly, and meets with the full Assembly each quarter to conduct any necessary business, such as appointing and approving committees; hearing reports from various officers of the Government; etc. All meetings of the Graduate Council are open to any graduate student in the University. GC meets every other week during the quarter and works closely with its ORCSA advisor to accomplish its goals. If you wish to be notified of upcoming events and meetings or you wish you become involved with the Council and its committees, please email the Council Chair.", website: "http://sg.uchicago.edu/")
Committee.create!(section: section, name: "BSD Dean's Council ", info: "The purpose of the Dean's Council is to advocate for graduate student issues and to organize and fund BSD social events. There are between 30 and 35 members who meet monthly throughout the academic year, and the group is aided by up to four administrators from graduate affairs and Dean Nancy Schwartz. The group is comprised of volunteers from each department within the BSD.", contact_info: "Parag Shah, Executive Administrator of the BSD Dean of Students Office, pshah@bsd.uchicago.edu")
Committee.create!(section: section, name: "Divinity Students Association (DSA) ", info: "The purpose of the DSA is to promote student enrichment, both academically through funding clubs and grants, and socially through extra-curricular activities. The DSA also runs the coffee shop. All Divinity School students are members and there are 3 elected officers, who meet several times per quarter.", contact_info: "Sarah Imhoff, sarahi@uchicago.edu")
Committee.create!(section: section, name: "Graduate Business Council ", info: "The GBC is the elected student body government for the GSB and acts as the umbrella organization for 55 full-time student groups. The GSB hosts a range of student organizations including career, cultural, diversity and social focused groups. The primary objective of the GBC is to maximize the student experience while at the GSB so that students can take full advantage of all the exceptional resources at the GSB and be excited about maintaining a link with Chicago GSB years after graduation. The GBC supports and enhances the overall experience of students and represents the entire student body to faculty and administration. GBC initiatives include grade disclosure/non-disclosure vote, weekly social events, winter formal, Distinguished Speakers Series, Chicago GSB-Kellogg Olympics, Random Walks, and the Mentor Program. From academics to social events and careers to clubs, the GBC has information on student groups, social events, career opportunities, and Chicago and Hyde Park events of interest to students.
                  
                  The GBC is made up of six executive officers as well as 20 other elected representatives from each cohort. Each cohort elects two representatives each Fall to serve on the council, making 4 total representatives per cohort (two from the first-year class and two from the second-year class). All students, faculty and staff are welcome to attend GBC meetings but only council members vote. The council meets approximately five times per quarter.", contact_info: "Jamie Rauch, GBC President, jrauch@uchicago.edu
Tara Sullivan, Director, Student Programs and Events, Full-Time MBA Program, Tara.Sullivan@chicagogsb.edu")

Committee.create!(section: section, name: "Booth School of Business Student Advisory Council (SAC) ", info: "The mission of the Student Advisory Council is to: (1) Facilitate connections between students, student groups, and Chicago Booth administration; (2) Execute activities with broad student appeal and foster community and relationships; (3) Encourage leadership within the part-time student body; and (4) Serve as a center for innovation and improvement within the Booth community.

SAC aims to enhance the Chicago Booth experience of the part time students. We understand the unique needs of our community and difficulties of managing work, school and personal lives at the same time. Chicago Booth offers more than an excellent academic education and SAC is here to make it easy for you to discover more. We are student leaders who believe in the importance of community, networking and a strong education.", contact_info: "Atul Modi, Co-President, atul.modi@chicagobooth.edu
Nikki Craig, Co-President, ncraig@chicagobooth.edu 
Holly Shearer, SAC Advisor, Holly.Shearer@chicagobooth.edu")

Committee.create!(section: section, name: "Humanities Division Graduate Student Council", info: "The Humanities Division Graduate Student Council comprises representatives from each of the departments and committees in the Division. The HDGSC's function is to allocate and monitor the funds returned to the Division from the Student Activity Fee.  It meets quarterly, and twice in the Spring, to review budget proposals from each of the departments and primarily funds events promoting inter and intra-departmental social activities. In the past, it has supported events such as the Department of Visual Arts Annual Open House, Pub Nights, Bowling Nights, graduate student conferences, and regular departmental social hours. The Council has a President and Vice President and its own constitution and by-laws, which it reviews as needed.", website: "http://hdgsc.uchicago.edu")

Committee.create!(section: section, name: "Law Students Association (LSA) ", info: "The Law Students Association (LSA) is the student government of the Law School. It is comprised of five elected representatives from each class, plus one elected representative from the L.L.M. candidates. The entire Law School elects te President of LSA, and LSA itself then fills the remaining positions. The activities include:
 LSA representatives also regularly interact with the Administration in making institutional planning decisions. To assist in this task, LSA has formed several committees: Academic Affairs (dealing with curriculum, appointments, etc.); Employment (working with Office of Career Services to better students' clerkship and career opportunities); Open to all students, these committees make specific recommendations to LSA about changes that would improve the Law School.", website: "http://www.law.uchicago.edu/current/studentorgs/lsa.html")
Committee.create!(section: section, name: "Pritzker School of Medicine Dean's Council", info: "The Dean's Council meets monthly and its function within Pritzker is to serve as a forum in which students can present, through class representatives, matters of concern ranging from medical school activities to hospital policies. Membership includes three representatives from each of Pritzker's four classes, and elected class representatives are expected to represent their colleagues' ideas and opinions at these meetings and act as liaisons between their medical colleagues and the Pritzker School of Medicine. First-year representatives rotate the responsibility of taking minutes and disseminating information from these meetings via email to the entire medical school. Any medical student organization or student-run activity desiring funding must apply through the Council. In addition, the Council administers the appropriation of, and distributes, medical student funds to various student organizations and functions. Applications for funding can be obtained on the Pritzker Student Portal, accessible through http://pritzker.bsd.uchicago.edu/current/students/organizations/deans_council.shtml. Elections for first year Dean's Council Representatives are held during the fall term of first year, at which time representatives are elected to a two year position. Candidates are elected for a second two-year term during the Clinical Biennium.", website: "http://pritzker.uchicago.edu/")
Committee.create!(section: section, name: "Physical Sciences Division (PSD) Student Social Committee ", info: "The Student Social Committee's purpose is to plan social, athletic, and cultural events for students in the PSD. They appropriate the funds from the student activities fee for the Division. The Committee meets 1-3 times per quarter and the number of volunteer members varies.", contact_info: "Rick Hefley, Dean of Students rhefley@midway.uchicago.edu", website: "http://psd.uchicago.edu")

Committee.create!(section: section, name: "Public Policy Student Association (PPSA) ", info: "PPSA is the elected student representative body of the Harris School. It serves as an advocate, communicating student concerns to the faculty and administration. It is comprised of six committees, a student ombudsperson, a graduate student council representative and the office of the President. Each is responsible for a different area of Harris students' lives, while the President's office is a communication and oversight body. In addition, the PPSA works to foster a strong community within and beyond the Harris School through a variety of events, activities, and community service efforts, as well as support and allocate funds for Harris School student organizations. Finally, the PPSA organizes and oversees the Amy Bosman Auction and Fellowship, which allows 3-6 students to participate in non-paid internships with higher callings.", website: "http://harrisschool.uchicago.edu/")
Committee.create!(section: section, name: "Student Government Association (SGA) of the School of Social Service Administration (SSA) ", info: "Student Government Association and the student organizations/activities of SSA provide students with the opportunity to express their views on a variety of issues of importance to the School and the profession of social work. Through their collaborative efforts, a system of mutual support for special events and activities is created within the student body. SGA and other student associations take an active role in the discussion of academic, professional, and political issues at SSA and in the community. In addition, SGA and the student groups also sponsor and co-sponsor various educational and social activities that enrich the graduate school experience.")
# 
# SSA student associations
Committee.create!(section: section, name: "Graduate Disciplinary Committees", info: "Each graduate division and school, and the Graham School of General Studies, has written procedures for disciplinary committees. Those procedures may be obtained in the Office of the Dean of Students of the division or school, or in the Office of the Dean of Students in the University. Many of the graduate areas do not have standing disciplinary committees. When a question of misconduct arises, a committee is appointed. Although committee structures vary somewhat, each committee has at least three members of the faculty. There may be (and at the insistence of the accused student must be) a student member on the committee, selected by the area Dean of Students. All voting members of the committee are from the appropriate division or school. Meetings convene as necessary.", contact_info: "Belinda Vazquez, Associate Dean of Students in the University for Student Affairs, belinda@uchicago.edu")


section = sections[5]

Committee.create!(section: section, name: "Student Health Advisory Board", info: "The purpose of the Student Health Advisory Board is to advise the Executive Medical Director and the Vice President for Campus Life on the health service needs of students at the University. The committee, comprised of students, administrators, Deans of Students and physicians, tries to balance the needs of students for high-quality comprehensive health care with financial constraints. The Committee meets two times a month during the academic year. Six students, 1-2 undergraduate and 4-5 graduate students, are appointed by Student Government.", contact_info: "Celia Bergman, Sr. Associate Dean of Students in the University for Student Health and Administrative Affairs, cbergman@uchicago.edu")



section = sections[6]

Committee.create!(section: section, name: "Committee on Crime Prevention and Security on Campus and in the Neighborhood", info: "The committee usually meets twice a year and advises the President of the University on a wide range of matters that may impact the safety of members of the University community or their property. A minimum of four students serve on the committee, and all are appointed by Student Government.", contact_info: "Duel Richardson, Director of Neighborhood Relations, duel@uchicago.edu
Office of Government and Community Affairs, (773) 702-6815 or sauc@midway.uchicago.edu")
Committee.create!(section: section, name: "Independent Review Committee for the UCPD", info: "The University of Chicago Police Department (UCPD) is a professional police force, deputized by the Superintendent of Police of the City of Chicago, with regular police powers while on duty in the areas of Hyde Park, Kenwood, North Kenwood and Woodlawn.  Over the years, the University police have performed a valuable service and demonstrated a commitment to the University community and the broader surrounding neighborhoods. From time to time however, complaints have been made about individual incidents or policies.  To ensure the campus and community's confidence in the University Police Department is maintained, the Independent Review Committee (IRC) reviews all complaints brought against University police relating directly or indirectly to issues of excessive force, violation of rights, or abusive language.  The Committee evaluates actions of UCPD and, when necessary, makes recommendations regarding UCPD's policies and procedures.  The Committee reports its findings and recommendations to the Provost and the Vice President for Civic Engagement.  A Committee report of all incidents including any recommended changes to policies and procedures is produced annually for the President and is distributed widely throughout the campus and community.", contact: "Ingrid Goulid, Associate Provost for Faculty and Student Affairs, igould@uchicago.edu")
Committee.create!(section: section, name: "All-University Disciplinary Committee", info: "The intent of student disciplinary procedures is to ensure a fair and orderly hearing on questions of possible student misconduct. A University Disciplinary Committee is empowered to conduct hearings on charges of violation by students of statutory provisions and Council legislation prohibiting disruptive acts. The last occasion for the convening of a University Disciplinary Committee came in 1974. Faculty and student panels are regularly appointed, however, in order that the Committee can be promptly convened should another occasion arise. Five undergraduate students nominated by SG and ten graduate students nominated by the divisional and school Deans of Students are annually selected to serve as potential members of the All-University Disciplinary Committee, which meets as necessary.", contact_info: "Belinda Vazquez, Associate Dean of Students in the University for Student Affairs, belinda@uchicago.edu")


section = sections[7]

Committee.create!(section: section, name: "Undergraduate Order of the C", info: "All undergraduate men lettering in a varsity sport are members. The purpose of the Order of the \"C\" is to support Varsity athletics and its student-athletes through program development and promotion of the University's athletics program. The membership is also involved in fundraising and community service in the Hyde Park and greater Chicagoland areas. The organization is represented by a board made up of seven elected executive members (President, VP, Treasurer, Secretary, Special Events Chair, two Concessions Coordinators) as well as two representatives from each of the 11 varsity sports. The board meets bi-weekly and also attends annual meetings with its alumni counterpart, the Graduate Order of the \"C\".", contact_info: "Scott Wiercinski, Advisor, swiercinski@uchicago.edu", website: "http://orderofc.uchicago.edu")
Committee.create!(section: section, name: "Women's Athletic Association (WAA)", info: "All women participating in a varsity sport are members. The purpose of the WAA is to support varsity athletics and to promote and develop the University's athletics program. The organization is composed of a student elected executive board and two team representatives from each varsity sport. This organization serves as the campus Student Athlete Advisory Committee (SAAC) and the President (or designee) represents the University of Chicago on the University Athletic Association conference SAAC. The group meets bi-weekly as an Executive Board, and monthly with team representatives.", contact_info: "Rosalie R. Resch, Advisor, rresch@uchicago.edu", website: "http://athletics.uchicago.edu/waa/waa.htm")

Committee.create!(section: section, name: "Coalition of Academic Teams (CAT)", info: "The Coalition of Academic Teams (CAT) is comprised of the leadership of the University's academic teams, including College Bowl, Debate Society, Mock Trial Team, Model UN Team and Chess Team, which each have their own systems of meetings and government. The coalition's purpose is to encourage, promote, and facilitate a broad mix of student-run competitive academic teams that will enrich the campus community and represent the University at competitions throughout the country. The number of members is 8, comprised of the ORCSA advisor, a representative from SG, and one representative from each member team. They meet annually for allocations and as needed throughout the year.", contact_info: "Dana Bozeman, Campus Activities Coordinator, ORCSA, dbozeman@uchicago.edu")

Committee.create!(section: section, name: "Maroon Advisory Board ", info: "The Chicago Maroon Advisory Board is the oversight board for the operations of the Chicago Maroon. There are 5 staff, 1 faculty member, and 2 students appointed by the Vice President and Dean of Students in the University and the Assistant Vice-President for Student Life, including the advisor, the managing editor, and the editor-in-chief.", contact_info: "Roberta Cohen, Deputy Dean of Students in the University, rcohen2@uchicago.edu
 Justin Sink, Editor-In-Chief of The Chicago Maroon, jsink@chicagomaroon.com")

Committee.create!(section: section, name: "WHPK Advisory Board", info: "The WHPK Advisory Board is the oversight board for the operations of the radio station WHPK. Five faculty and staff and five students comprise the committee. Three students are elected by the station and the student station manager and student program director also serve on the Board.", contact_info: "Stacey Ergang, Assistant Director for Student Development, ORCSA,sergang@uchicago.edu", website: "http://whpk.uchicago.edu/info/")


section = sections[8]

Committee.create!(section: section, name: "Community Service Fund (CSF)", info: "CSF provides grants to University Community Service Recognized Student Organizations (CSRSOs) and to community service projects by Recognized Student Organizations (RSOs). There are 55 CSRSOs eligible to apply for funds for community service initiatives. The CSF selection committee consisting of Student Government, CSRSO and University Community Service Center (UCSC) representatives who meet quarterly to review funding for that specific quarter and once annually to review year-long CSRSO funding proposals. CSF Annual Allocations are limited to CSRSOs.", contact_info: "Wallace E. Goode, Jr., Director, UCSC, wgoode@uchiago.edu", website: "http://communityservice.uchicago.edu/")
Committee.create!(section: section, name: "Sport Club Quarterly Allocation and Annual Committees", info: " The Sport Club Annual Finance Committee recommends Student Activity Fee Funds to Sport Clubs for activities sponsored by one or more Sport Club. Financial support by the Finance Committee is based on consideration of the athletic, artistic, social, intellectual, educational, cultural and/or informational contribution made directly or indirectly to the University community by the activity. A Sport Club Quarterly Finance Committee is selected at the start of Fall Quarter. The representation of the committee is comprised of approximately ten students - all of whom are members of individual Sport Clubs.  The Quarterly Finance Committee considers quarterly funding requests every Monday evening through the 9th week of each quarter. Requests should be submitted by noon on Fridays to the Sport Club Office (Ratner Rm 141). The Sport Club Quarterly allocation funds both Sport Club special events and general operating expenses; unlike the Annual Allocation Committee, the Finance Committee distributes funds to groups on a short-term, event-by-event basis.", website: "http://athletics.uchicago.edu/campus/sport-clubs.htm") 
Committee.create!(section: section, name: "Student Fine Arts Fund of the University Arts Council", info: "The goal of the SFAF is to fund arts-related projects originating from students that fall outside of the kinds of projects normally funded by RSOs or departments. SFAF encourages the development of arts projects that are interdisciplinary by awarding grants of up to $1500. Students are selected from the leadership of student art organizations. The number of members is 3 administrators and 6-7 students; Student Government will appoint 2 students and the remaining students will be elected to represent the various artistic disciplines at the University. The group meets quarterly.", contact_info: "Heidi Coleman, Director of University Theater,coleman@uchicago.edu", website: "http://www.uchicago.edu/artscouncil/fineartsfund.shtml")
Committee.create!(section: section, name: "Committee on Recognized Student Organizations (CORSO) of Student Government", info: "The main purpose of CORSO is to serve and aid RSOs in every possible way. This group is the main advisory board to the Office of the Reynolds Club and Student Activities (ORCSA), which oversees all of the Registered Student Organizations in the University and provides them with several services. As a liason between the RSOs and ORCSA, CORSO does outreach to student groups and addresses their concerns and needs. CORSO is also responsible for reviewing applications from groups attempting to become an RSO and for putting on events that inform and respond to the needs of all groups. The committee consists of three elected members from the SG Assembly and three members who are nominated from among student leaders and appointed by ORCSA.", contact_info: "Toussaint Losier, SG VP for Student Affairs,tlosier@uchicago.edu")



section = sections[9]

Committee.create!(section: section, name: "Student Ombudsperson Selection Committee", info: "The Ombudsman Selection Committee meets in the spring of every year to interview the finalist candidate(s) for ombudsperson and associate ombudsperson and to make a committee recommendation to the President, who hires the two students for these positions. The Selection Committee has two students appointed by Student Government (one graduate, one undergraduate), two faculty members, one staff member, and the ombudsperson.", contact_info: "Celia Bergman, Sr. Associate Dean of Students in the University for Student Health and Administrative Affairs, cbergman@uchicago.edu")
Committee.create!(section: section, name: "Student Government: Student Life",info: "The Committee on Student Life will work to improve the lives of students by focusing on a variety of student concerns including minority and activist issues, health insurance concerns, community relations, and will also run the complaints.uchicago.edu website. This committee also runs the SG/RSO Variety Show at Summer Breeze. The Variety Show will showcase different performance organizations and gives them a chance to expose themselves to the campus community. The committee will address activist and minority concerns ranging from University Employment issues, community relations with the University, the Universities policies toward non-political stances or the Kalven Report, and the new Diversity Center coming to campus. A member will serve on the University Committee on Minority Affairs. The committee is also charged with the task of evaluating a variety of University polices effecting student health issues (i.e. Health Insurance/Packages) and will meeting with administrators and slate members to evaluate the effectiveness of university policies and cost in all health fields. The members of this committee will field all complaints from the Student Government complaints website and respond to those complaints as well as visit different houses and student organizations on campus to talk to students about their concerns. Members of the Student Life Committee interested in community serve will have an opportunity to work on improving relations between the university community and its surrounding neighborhoods by working with neighborhood leaders to foster a better working relationship and serving on university committees including the Student Advisory Committee on the Neighborhood and the Community Service Fund Council.", contact_info: "Toussaint Losier, SG Vice President and Advisor, tlosier@uchicago.edu")


section = sections[10]

Committee.create!(section: section, name: "Student Government", info: "Student Government (SG) at the University of Chicago works to improve student life on campus and represents students' interest to the administration. From running pilot programs to offer airport shuttles to creating factoids.uchicago.edu, fielding student complaints, and putting on a Variety Show at Summer Breeze, SG is successful at addressing the concerns on campus.

                  The president, two vice presidents, two student liaisons to the Board of Trustees, and SG’s legislative assembly (the College Council and Graduate Council) create committees that focus on issues ranging from student services to community relations and more. SG members vote on campus matters, allocate student activities fee funds, serve on SG and University wide committees, and help make the University of Chicago a better place for students to learn and grow. To learn more about how to get involved in the committees, or run for the College or Graduate Council, visit the SG website at sg.uchicago.edu.", contact_info: "
 Greg Nance, President of Student Government, nance@uchicago.edu
                 
 David Chen, SG VP for Administration, davidchen@uchicago.edu

 Patrick Ip, SG VP for Student Affairs, pip@uchicago.edu")

Committee.create!(section: section, name: "College Council (CC)", info: "The College Council is the undergraduate legislative body of Student Government. The Council consists of 15 positions: four first-year Class Officers, four second-year Class Officers, three third-year Class Officers, three fourth-year Class Officers, and one \"n-th\" year representative. The committee is run by a Chair and Vice Chair that are appointed at the first meeting of the year. College Council members approve all decisions of the Student Government Finance Committee (SGFC), draft and approve proposals brought forth on a variety of student issues including University of Chicago Police Department (UCPD)/student relations, the University Diversity Statement, and the University Sexual Harassment Policy, and also serve on an assortment of SG and University committees. Election to the College Council takes place during the third week of Fall Quarter and petitions are available online at the SG website, sg.uchicago.edu, or in the SG office, Reynolds Club 010. If you are interested in addressing student concerns, putting on events, or funding all organizations on campus, College Council is the perfect place for you.", contact_info: "Jason Cigan, Chair, jcigan@uchicago.edu")

Committee.create!(section: section, name: "Graduate Council (GC)", info: "The Graduate Council is the graduate student half of the Assembly of the Student Government of the University of Chicago. The Council's purpose is to effectively represent the graduate student body and foster interaction between students from diverse disciplines. GC represents graduate students of all divisions and professional schools and is funded by graduate student activities fees, which all students pay upon registration.

                  Graduate Council rewards, respects, and represents U of C graduate students by sponsoring events, creating a forum for the discussion of graduate student issues, and participating in the Student Government Assembly. In the recent past, GC has sponsored many events including pub nights, dances, relaxation days, and trips to sporting events. GC has made significant progress increasing awareness of graduate student issues such as student health insurance, safety, and transportation. GC wants to ensure graduate students get everything they deserve from their U of C experience.

                  We have all worked hard to get this far and now that we are here we should be able to enjoy it. YOU DESERVE THE BEST! With graduate student participation and feedback, Graduate Council can make this year better than ever, but we NEED you! You are our constituents and we need to know what you want. Having problems with your program? Want to tackle a graduate student issue? Have an idea for a graduate student event? GC is the place you should be! We can connect you with the funding, resources, and people to make it happen. Every U of C division and professional school has one or two voting representatives on the council.

                  Voting representatives are usually elected by the divisional council at the start of Fall Quarter; contact your divisional council or GC for more information. Non-voting representatives are also an important component of GC. Any graduate student may participate in GC meetings and committees without being officially elected. We generally meet twice a month and provide free dinners for attending students. Graduate Council has several committees focused on different topics that meet on the off-weeks. These committees are: the Events Committee, Issues Committee, Finance Committee, and Graduate Funding Committee. If you are interested in learning about our events, you can sign up for the GC Events Listhost: gcevents@listhost.uchicago.edu. If you are interested in becoming involved with Graduate Council through one of the committees of GC or a University-wide SG committee, please contact the Chair of the Council.", contact_info: "
                  Alison Baulos, Chair, abaulos@uchicago.edu

                  Jigna Shah, Associate Director, ORCSA, jigna@uchicago.edu", website: "http://sg.uchicago.edu/")


section = sections[11]

Committee.create!(section: section, name: "The Student Liasons to the University Board of Trustees", info: "The College and Graduate Student Liaisons to the University Board of Trustees are elected to represent the interests and desires of the student body to the Board. The Liaisons interpret the wide range of concerns and issues of the quite varied student body and advocates for both long-range and short-term issues to the Board. The Liaison works closely with the SG Executive Slate, key University administrators, and meets with the Board of Trustees, usually through the Trustee Committee on Student Life.", contact_info: "Frank Alarcon, College Student Liaison to the University Board of Trustees, falarcon@uchicago.edu

Jordan Phillips, Graduate Student Liaison to the University Board of Trustees, jordanp@uchicago.edu", website: "http://sg.uchicago.edu")

Committee.create!(section: section, name: " Programming Coordinating Council of Student Government", info: "The Programming and Coordinating Council brings together the biggest programming groups on campus. COUP, DOC, MAB, University Theater, WHPK, and Fire Escape Films, are part of this committee. The main purpose of this committee is to bring these programming groups together throughout the year in order to foster communication and cooperation amongst them. This not only allows for the groups to know what the others are doing, but also to learn from each other and plan events together where their interests or goals are similar. Being part of PCC will allow you to learn about what these groups are doing, how they work, and you will also become a vital part of the communication and decision-making process. Most importantly, you will have a voice in the allocation of over $350,000. The membership of the committee is made up of heads of the 6 major programming groups and 3 students elected from and by the SG Assembly.", contact: "Toussaint Losier, Chair, SG VP for Student Affairs, tlosier@uchicago.edu", website: "http://sg.uchicago.edu")

Committee.create!(section: section, name: "Student Government Finance Committee of Student Government", info: "The SG Finance Committee (SGFC) is responsible for allocating money to all 300+ Registered Student Organizations (RSO) on campus. It is comprised of seven elected members: three graduate students, three undergraduate students, and a chair appointed by the Executive Slate. If you are involved with the finances or the planning of events for an RSO, then you should join SGFC. Your perspective will help insure that funds are distributed generously and fairly. Students can join SGFC by election from the SG Assembly only. The committee must be comprised of at least three undergraduates and at least 3 graduates, not to exceed seven members. The Executive Committee of Student Government then appoints a chairperson. SGFC meets every Tuesday during the year.", website: "http://sg.uchicago.edu")

Committee.create!(section: section, name: "Committee on Recognized Student Organizations (CORSO) of Student Government", info: "The main purpose of CORSO is to serve and aid RSOs in every possible way. This group is the main advisory board to the Office of the Reynolds Club and Student Activities (ORCSA), which oversees all of the Registered Student Organizations in the University and provides them with several services. As a liason between the RSOs and ORCSA, CORSO does outreach to student groups and addresses their concerns and needs. CORSO is also responsible for reviewing applications from groups attempting to become an RSO and for putting on events that inform and respond to the needs of all groups. The committee consists of three elected members from the SG Assembly and three members who are nominated from among student leaders and appointed by ORCSA.", contact_info: "Toussaint Losier, SG Vice President and Advisor, tlosier@uchicago.edu", website: "http://sg.uchicago.edu")


section = sections[12]

Committee.create!(section: section, name: "Student Life Committee", info: "The Committee on Student Life will work to improve the lives of students by focusing on a variety of student concerns including minority and activist issues, health insurance concerns, community relations, and will also run the complaints.uchicago.edu website. This committee also runs the SG/RSO Variety Show at Summer Breeze. The Variety Show will showcase different performance organizations and gives them a chance to expose themselves to the campus community. The committee will address activist and minority concerns ranging from University Employment issues, community relations with the University, the Universities policies toward non-political stances or the Kalven Report, and the new Diversity Center coming to campus. A member will serve on the University Committee on Minority Affairs. The committee is also charged with the task of evaluating a variety of University polices effecting student health issues (i.e. Health Insurance/Packages) and will meeting with administrators and slate members to evaluate the effectiveness of university policies and cost in all health fields. The members of this committee will field all complaints from the Student Government complaints website and respond to those complaints as well as visit different houses and student organizations on campus to talk to students about their concerns. Members of the Student Life Committee interested in community serve will have an opportunity to work on improving relations between the university community and its surrounding neighborhoods by working with neighborhood leaders to foster a better working relationship and serving on university committees including the Community Service Fund.", contact_info: "Matt Kennedy, SG President, mkennedy@uchicago.edu")

Committee.create!(section: section, name: "Campus Services Committee", info: "The Committee on Campus Services addresses concerns pertaining to transportation, security, dining, on campus banking, and academics at the University. Members interested in transportation will work with Chicago Transit Authority (CTA) and the Administrative Transportation committees including the Late Night Transportation Committee and Transportation Advisory Work Group in order to improve the transit routes to, from and around campus as well as parking lot space. From the A-F route, the 171/2/3 and the Late Night Van Service, members of this committee will ensure the campus transportation system is working effectively at all times and for all students. Other members will work sit on and work closely with the UofC Committee on Safety and Security, Independent Review Committee for the University of Chicago Police Department, and the All University Disciplinary Committee with the aim of creating a safe environment for all members of the University. In the area of dining, members will serve on the university Campus Dining Advisory Board which will focus on oversight and student response on the quality and structure on the Campus Dining Services. Members interested in banking will have an opportunity to work with the university bursar and the manager of Citibank with the purpose of advising the administration on issues of banking services provided to students.Members will also deal with academic services on campus including Cmore, course evaluations and class times and availability. Past contributions from the Committee on Campus Services include the development of a new events website that is expected to launch in 2006, leading a project to install a camera on the side of Eckhart and an LCD screen in the Reynolds Club to display information and allow people to watch for the buses while waiting inside during the winter, Created http://factoids.uchicago.edu to disseminate useful facts for students, Categorized and prioritized student complaints to NSIT about cMail, and audited the Regenstein library facilities problems (broken thermostats, etc.) and reported them to Facilities Services, along with various other facilities problems around campus.", contact_info: "Chris Williams, Campus Services Chair, chriswilliams@uchicago.edu", website: "http://sg.uchicago.edu")

Committee.create!(section: section, name: "Student Government Association (SGA) of the School of Social Service Administration (SSA)", info: "Student Government Association and the student organizations/activities of SSA provide students with the opportunity to express their views on a variety of issues of importance to the School and the profession of social work. Through their collaborative efforts, a system of mutual support for special events and activities is created within the student body. SGA and other student associations take an active role in the discussion of academic, professional, and political issues at SSA and in the community. In addition, SGA and the student groups also sponsor and co-sponsor various educational and social activities that enrich the graduate school experience.", contact_info: "Eugene Robinson, President, erobinsonjr@uchicago.edu
                
Chastity Rolling, Vice-President, rolling@uchicago.edu", website: "http://www.ssa.uchicago.edu/students/student-associations.shtml")






